[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[build]
target = "i686-unknown-linux-gnu"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core"]
#build-std = ["core", "compiler_builtins"]

