[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[build]
target = "i686-unknown-linux-gnu"
#build-std-features = ["compiler-builtins-mem"]
#build-std = ["core"]

#[unstable]
#build-std-features = ["compiler-builtins-mem"]
#build-std = ["core"]
#build-std-features = ["core", "compiler_builtins"]
